# Generated by Django 2.0 on 2024-12-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0004_questions_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option1',
            new_name='optiona',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option2',
            new_name='optionb',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option3',
            new_name='optionc',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option4',
            new_name='optiond',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_mark',
        ),
    ]
