# Generated by Django 2.0 on 2024-12-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0005_auto_20241211_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='answer',
            new_name='pass_fail',
        ),
        migrations.AddField(
            model_name='result',
            name='passmark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_reply',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='education_content',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prediction_result',
            name='prediction_result',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.CharField(max_length=500),
        ),
    ]
