# Generated by Django 2.0 on 2024-12-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0006_auto_20241211_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(default='NO', max_length=50),
        ),
    ]
