# Generated by Django 2.0 on 2024-12-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0007_auto_20241212_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_reply',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
