# Generated by Django 2.0 on 2024-12-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0008_auto_20241212_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
