# Generated by Django 2.0 on 2025-01-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0011_auto_20241223_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_content',
            name='content_type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
