# Generated by Django 2.0 on 2025-01-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0012_education_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_content',
            name='difficulty',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education_content',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
