# Generated by Django 2.0 on 2025-01-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0013_auto_20250106_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='education_content',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='education_content',
            name='file_type',
        ),
        migrations.AddField(
            model_name='video_content',
            name='EDUCATION_CONTENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptitudeApp.Education_Content'),
        ),
    ]
