# Generated by Django 2.0 on 2025-01-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0014_auto_20250113_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_content',
            old_name='path',
            new_name='link',
        ),
    ]
