# Generated by Django 2.0 on 2025-01-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0015_auto_20250113_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question_level',
            new_name='difficulty',
        ),
    ]
