# Generated by Django 2.0 on 2025-01-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0016_auto_20250115_1205'),
        ('AptitudeApp', '0017_auto_20250119_2221'),
    ]

    operations = [
    ]
