# Generated by Django 2.0 on 2025-01-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0019_auto_20250121_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='mark',
            new_name='logical_score',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='result_date',
            new_name='mark_scored',
        ),
        migrations.RemoveField(
            model_name='result',
            name='passmark',
        ),
        migrations.AddField(
            model_name='result',
            name='quant_score',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='verbal_score',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test_num_of_qns_logical',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test_num_of_qns_quantitative',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test_num_of_qns_verbal',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
