# Generated by Django 2.0 on 2025-01-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0020_auto_20250125_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='TESTQUESTION',
        ),
        migrations.AddField(
            model_name='result',
            name='TEST',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AptitudeApp.Test'),
            preserve_default=False,
        ),
    ]
