# Generated by Django 2.0 on 2025-01-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0021_auto_20250127_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=5000)),
                ('optiona', models.CharField(max_length=500)),
                ('optionb', models.CharField(max_length=500)),
                ('optionc', models.CharField(max_length=500)),
                ('optiond', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('EDUCATION_CONTENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptitudeApp.Education_Content')),
            ],
        ),
        migrations.CreateModel(
            name='User_Educontent_Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.CharField(default='No', max_length=500)),
                ('EDUCATION_CONTENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptitudeApp.Education_Content')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptitudeApp.User')),
            ],
        ),
    ]
