# Generated by Django 3.0 on 2025-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0022_section_test_user_educontent_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=5000)),
                ('optiona', models.CharField(max_length=500)),
                ('optionb', models.CharField(max_length=500)),
                ('optionc', models.CharField(max_length=500)),
                ('optiond', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('question_type', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('answer_description', models.CharField(max_length=5000)),
            ],
        ),
    ]
