# Generated by Django 3.0 on 2025-03-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0023_tempquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.CharField(max_length=500)),
                ('improvment_rate', models.CharField(max_length=500)),
                ('difficulty_score', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptitudeApp.User')),
            ],
        ),
    ]
