# Generated by Django 3.0 on 2025-03-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0024_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CP_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.CharField(max_length=50)),
                ('test_difficulty', models.CharField(max_length=50)),
                ('test_num_of_qns', models.CharField(max_length=50)),
                ('test_num_of_qns_logical', models.CharField(max_length=50)),
                ('test_num_of_qns_quantitative', models.CharField(max_length=50)),
                ('test_num_of_qns_verbal', models.CharField(max_length=50)),
                ('test_time', models.CharField(max_length=50)),
                ('test_topics', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptitudeApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='CP_Test_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CP_TEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptitudeApp.CP_Test')),
                ('QUESTIONS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptitudeApp.Questions')),
            ],
        ),
    ]
