# Generated by Django 3.0 on 2025-03-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0025_cp_test_cp_test_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cp_test_question',
            name='CP_TEST',
        ),
        migrations.RemoveField(
            model_name='cp_test_question',
            name='QUESTIONS',
        ),
        migrations.DeleteModel(
            name='CP_Test',
        ),
        migrations.DeleteModel(
            name='CP_Test_Question',
        ),
    ]
