# Generated by Django 3.0 on 2025-03-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0026_auto_20250322_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='cp',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
