# Generated by Django 3.0 on 2025-03-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0027_test_cp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=500)),
                ('job_description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('answer_description', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='cp',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
