# Generated by Django 3.0 on 2025-03-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitudeApp', '0028_auto_20250323_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
    ]
